import XCTest
@testable import AXML

final class AXMLtoXMLTests: XCTestCase {
    func testAXMLConversion() throws {
        // Given
        let axml = Data(base64Encoded: input)!

        // When
        let xml = try axmlToXml(axml)

        // Then
        XCTAssertEqual(String(decoding: xml, as: UTF8.self), expected)
    }
}

// swiftlint:disable line_length
let input = "AwAIACAVAAABABwAkAsAAD0AAAAAAAAAAAAAABABAAAAAAAAAAAAAA4AAAAcAAAAKAAAADQAAABIAAAAYgAAAHIAAAB+AAAAnAAAALYAAADQAAAA9AAAAA4BAAAqAQAATAEAAGoBAACEAQAAqgEAANABAAAGAgAAMAIAAD4CAABEAgAAVAIAAGgCAAB6AgAAsgIAAOoCAAAwAwAAcgMAALYDAADwAwAARAQAAJoEAADqBAAABAUAABgFAABkBQAAcAUAAJoFAADeBQAANgYAAJoGAAD+BgAAWAcAAL4HAAAkCAAAiggAAN4IAADqCAAAQgkAAGAJAAB0CQAAhgkAALoJAADuCQAAAgoAACYKAABICgAAXAoAAAUAdABoAGUAbQBlAAAABQBsAGEAYgBlAGwAAAAEAGkAYwBvAG4AAAAEAG4AYQBtAGUAAAAIAGUAeABwAG8AcgB0AGUAZAAAAAsAYQB1AHQAaABvAHIAaQB0AGkAZQBzAAAABgBzAGMAaABlAG0AZQAAAAQAaABvAHMAdAAAAA0AbQBpAG4AUwBkAGsAVgBlAHIAcwBpAG8AbgAAAAsAdgBlAHIAcwBpAG8AbgBDAG8AZABlAAAACwB2AGUAcgBzAGkAbwBuAE4AYQBtAGUAAAAQAHQAYQByAGcAZQB0AFMAZABrAFYAZQByAHMAaQBvAG4AAAALAGEAbABsAG8AdwBCAGEAYwBrAHUAcAAAAAwAbABhAHIAZwBlAFMAYwByAGUAZQBuAHMAAAAPAGkAbgBzAHQAYQBsAGwATABvAGMAYQB0AGkAbwBuAAAADQB4AGwAYQByAGcAZQBTAGMAcgBlAGUAbgBzAAAACwBzAHUAcABwAG8AcgB0AHMAUgB0AGwAAAARAGYAdQBsAGwAQgBhAGMAawB1AHAAQwBvAG4AdABlAG4AdAAAABEAYwBvAG0AcABpAGwAZQBTAGQAawBWAGUAcgBzAGkAbwBuAAAAGQBjAG8AbQBwAGkAbABlAFMAZABrAFYAZQByAHMAaQBvAG4AQwBvAGQAZQBuAGEAbQBlAAAAEwBhAHAAcABDAG8AbQBwAG8AbgBlAG4AdABGAGEAYwB0AG8AcgB5AAAABQAyAC4AOAAuADAAAAABADkAAAAGAGEAYwB0AGkAbwBuAAAACABhAGMAdABpAHYAaQB0AHkAAAAHAGEAbgBkAHIAbwBpAGQAAAAaAGEAbgBkAHIAbwBpAGQALgBpAG4AdABlAG4AdAAuAGEAYwB0AGkAbwBuAC4ATQBBAEkATgAAABoAYQBuAGQAcgBvAGkAZAAuAGkAbgB0AGUAbgB0AC4AYQBjAHQAaQBvAG4ALgBWAEkARQBXAAAAIQBhAG4AZAByAG8AaQBkAC4AaQBuAHQAZQBuAHQALgBjAGEAdABlAGcAbwByAHkALgBCAFIATwBXAFMAQQBCAEwARQAAAB8AYQBuAGQAcgBvAGkAZAAuAGkAbgB0AGUAbgB0AC4AYwBhAHQAZQBnAG8AcgB5AC4ARABFAEYAQQBVAEwAVAAAACAAYQBuAGQAcgBvAGkAZAAuAGkAbgB0AGUAbgB0AC4AYwBhAHQAZQBnAG8AcgB5AC4ATABBAFUATgBDAEgARQBSAAAAGwBhAG4AZAByAG8AaQBkAC4AcABlAHIAbQBpAHMAcwBpAG8AbgAuAEkATgBUAEUAUgBOAEUAVAAAACgAYQBuAGQAcgBvAGkAZAAuAHAAZQByAG0AaQBzAHMAaQBvAG4ALgBSAEUAQQBEAF8ARQBYAFQARQBSAE4AQQBMAF8AUwBUAE8AUgBBAEcARQAAACkAYQBuAGQAcgBvAGkAZAAuAHAAZQByAG0AaQBzAHMAaQBvAG4ALgBXAFIASQBUAEUAXwBFAFgAVABFAFIATgBBAEwAXwBTAFQATwBSAEEARwBFAAAAJgBhAG4AZAByAG8AaQBkAHgALgBjAG8AcgBlAC4AYQBwAHAALgBDAG8AcgBlAEMAbwBtAHAAbwBuAGUAbgB0AEYAYQBjAHQAbwByAHkAAAALAGEAcABwAGwAaQBjAGEAdABpAG8AbgAAAAgAYwBhAHQAZQBnAG8AcgB5AAAAJABjAG8AbQAuAHMAcQB1AGEAcgBlAHUAcAAuAHAAaQBjAGEAcwBzAG8ALgBQAGkAYwBhAHMAcwBvAFAAcgBvAHYAaQBkAGUAcgAAAAQAZABhAHQAYQAAABMAZABlAC4AYwBpAG4AZQBhAHMAdABlAC4AYQBuAGQAcgBvAGkAZAAAACAAZABlAC4AYwBpAG4AZQBhAHMAdABlAC4AYQBuAGQAcgBvAGkAZAAuAE0AYQBpAG4AQQBjAHQAaQB2AGkAdAB5AAAAKgBkAGUALgBjAGkAbgBlAGEAcwB0AGUALgBhAG4AZAByAG8AaQBkAC4AYQBjAHQAaQB2AGkAdAB5AC4AQQBiAG8AdQB0AEEAYwB0AGkAdgBpAHQAeQAAADAAZABlAC4AYwBpAG4AZQBhAHMAdABlAC4AYQBuAGQAcgBvAGkAZAAuAGEAYwB0AGkAdgBpAHQAeQAuAE0AbwB2AGkAZQBEAGUAdABhAGkAbABBAGMAdABpAHYAaQB0AHkAAAAwAGQAZQAuAGMAaQBuAGUAYQBzAHQAZQAuAGEAbgBkAHIAbwBpAGQALgBhAGMAdABpAHYAaQB0AHkALgBNAG8AdgBpAGUAUwBlAGEAcgBjAGgAQQBjAHQAaQB2AGkAdAB5AAAAKwBkAGUALgBjAGkAbgBlAGEAcwB0AGUALgBhAG4AZAByAG8AaQBkAC4AYQBjAHQAaQB2AGkAdAB5AC4AUABvAHMAdABlAHIAQQBjAHQAaQB2AGkAdAB5AAAAMQBkAGUALgBjAGkAbgBlAGEAcwB0AGUALgBhAG4AZAByAG8AaQBkAC4AYQBjAHQAaQB2AGkAdAB5AC4AUwBlAGEAcwBvAG4ARABlAHQAYQBpAGwAQQBjAHQAaQB2AGkAdAB5AAAAMQBkAGUALgBjAGkAbgBlAGEAcwB0AGUALgBhAG4AZAByAG8AaQBkAC4AYQBjAHQAaQB2AGkAdAB5AC4AUwBlAHIAaQBlAHMARABlAHQAYQBpAGwAQQBjAHQAaQB2AGkAdAB5AAAAMQBkAGUALgBjAGkAbgBlAGEAcwB0AGUALgBhAG4AZAByAG8AaQBkAC4AYQBjAHQAaQB2AGkAdAB5AC4AUwBlAHIAaQBlAHMAUwBlAGEAcgBjAGgAQQBjAHQAaQB2AGkAdAB5AAAAKABkAGUALgBjAGkAbgBlAGEAcwB0AGUALgBhAG4AZAByAG8AaQBkAC4AYwBvAG0ALgBzAHEAdQBhAHIAZQB1AHAALgBwAGkAYwBhAHMAcwBvAAAABABoAHQAdABwAAAAKgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBhAG4AZAByAG8AaQBkAC4AYwBvAG0ALwBhAHAAawAvAHIAZQBzAC8AYQBuAGQAcgBvAGkAZAAAAA0AaQBuAHQAZQBuAHQALQBmAGkAbAB0AGUAcgAAAAgAbQBhAG4AaQBmAGUAcwB0AAAABwBwAGEAYwBrAGEAZwBlAAAAGABwAGwAYQB0AGYAbwByAG0AQgB1AGkAbABkAFYAZQByAHMAaQBvAG4AQwBvAGQAZQAAABgAcABsAGEAdABmAG8AcgBtAEIAdQBpAGwAZABWAGUAcgBzAGkAbwBuAE4AYQBtAGUAAAAIAHAAcgBvAHYAaQBkAGUAcgAAABAAcwB1AHAAcABvAHIAdABzAC0AcwBjAHIAZQBlAG4AcwAAAA8AdQBzAGUAcwAtAHAAZQByAG0AaQBzAHMAaQBvAG4AAAAIAHUAcwBlAHMALQBzAGQAawAAAA8AdwB3AHcALgBjAGkAbgBlAGEAcwB0AGUALgBkAGUAAAAAAIABCABcAAAAAAABAQEAAQECAAEBAwABARAAAQEYAAEBJwABASgAAQEMAgEBGwIBARwCAQFwAgEBgAIBAYYCAQG3AgEBvwIBAa8DAQHrBAEBcgUBAXMFAQF6BQEBAAEQABgAAAACAAAA/////xkAAAAyAAAAAgEQAMQAAAACAAAA//////////80AAAAFAAUAAgAAAAAAAAAMgAAAAkAAAD/////CAAAEBIAAAAyAAAACgAAABUAAAAIAAADFQAAADIAAAAOAAAA/////wgAABAAAAAAMgAAABIAAAD/////CAAAEBwAAAAyAAAAEwAAABYAAAAIAAADFgAAAP////81AAAAJwAAAAgAAAMnAAAA/////zYAAAD/////CAAAEBwAAAD/////NwAAAP////8IAAAQCQAAAAIBEABMAAAACAAAAP//////////OwAAABQAFAACAAAAAAAAADIAAAAIAAAA/////wgAABATAAAAMgAAAAsAAAD/////CAAAEBwAAAADARAAGAAAAAgAAAD//////////zsAAAACARAATAAAAAwAAAD//////////zkAAAAUABQAAgAAAAAAAAAyAAAADQAAAP////8IAAAS/////zIAAAAPAAAA/////wgAABL/////AwEQABgAAAAMAAAA//////////85AAAAAgEQADgAAAAQAAAA//////////86AAAAFAAUAAEAAAAAAAAAMgAAAAMAAAAfAAAACAAAAx8AAAADARAAGAAAABAAAAD//////////zoAAAACARAAOAAAABEAAAD//////////zoAAAAUABQAAQAAAAAAAAAyAAAAAwAAACAAAAAIAAADIAAAAAMBEAAYAAAAEQAAAP//////////OgAAAAIBEAA4AAAAEgAAAP//////////OgAAABQAFAABAAAAAAAAADIAAAADAAAAIQAAAAgAAAMhAAAAAwEQABgAAAASAAAA//////////86AAAAAgEQALAAAAAUAAAA//////////8jAAAAFAAUAAcAAAAAAAAAMgAAAAAAAAD/////CAAAAQYAEX8yAAAAAQAAAP////8IAAABKQAQfzIAAAACAAAA/////wgAAAEAAA1/MgAAAAwAAAD/////CAAAEv////8yAAAAEAAAAP////8IAAAS/////zIAAAARAAAA/////wgAABL/////MgAAABQAAAAiAAAACAAAAyIAAAACARAAOAAAABwAAAD//////////xgAAAAUABQAAQAAAAAAAAAyAAAAAwAAACgAAAAIAAADKAAAAAIBEAAkAAAAHQAAAP//////////MwAAABQAFAAAAAAAAAAAAAIBEAA4AAAAHgAAAP//////////FwAAABQAFAABAAAAAAAAADIAAAADAAAAGgAAAAgAAAMaAAAAAwEQABgAAAAeAAAA//////////8XAAAAAgEQADgAAAAgAAAA//////////8kAAAAFAAUAAEAAAAAAAAAMgAAAAMAAAAeAAAACAAAAx4AAAADARAAGAAAACAAAAD//////////yQAAAADARAAGAAAAB0AAAD//////////zMAAAACARAAJAAAACIAAAD//////////zMAAAAUABQAAAAAAAAAAAACARAAOAAAACUAAAD//////////xcAAAAUABQAAQAAAAAAAAAyAAAAAwAAABsAAAAIAAADGwAAAAMBEAAYAAAAJQAAAP//////////FwAAAAIBEAA4AAAAJwAAAP//////////JAAAABQAFAABAAAAAAAAADIAAAADAAAAHQAAAAgAAAMdAAAAAwEQABgAAAAnAAAA//////////8kAAAAAgEQADgAAAAoAAAA//////////8kAAAAFAAUAAEAAAAAAAAAMgAAAAMAAAAcAAAACAAAAxwAAAADARAAGAAAACgAAAD//////////yQAAAACARAATAAAACoAAAD//////////yYAAAAUABQAAgAAAAAAAAAyAAAABgAAADEAAAAIAAADMQAAADIAAAAHAAAAPAAAAAgAAAM8AAAAAwEQABgAAAAqAAAA//////////8mAAAAAwEQABgAAAAiAAAA//////////8zAAAAAwEQABgAAAAcAAAA//////////8YAAAAAgEQAEwAAAAvAAAA//////////8YAAAAFAAUAAIAAAAAAAAAMgAAAAAAAAD/////CAAAAcoAEX8yAAAAAwAAACoAAAAIAAADKgAAAAMBEAAYAAAALwAAAP//////////GAAAAAIBEAA4AAAAMgAAAP//////////GAAAABQAFAABAAAAAAAAADIAAAADAAAAKwAAAAgAAAMrAAAAAwEQABgAAAAyAAAA//////////8YAAAAAgEQADgAAAAzAAAA//////////8YAAAAFAAUAAEAAAAAAAAAMgAAAAMAAAApAAAACAAAAykAAAADARAAGAAAADMAAAD//////////xgAAAACARAAOAAAADQAAAD//////////xgAAAAUABQAAQAAAAAAAAAyAAAAAwAAACwAAAAIAAADLAAAAAMBEAAYAAAANAAAAP//////////GAAAAAIBEAA4AAAANQAAAP//////////GAAAABQAFAABAAAAAAAAADIAAAADAAAALwAAAAgAAAMvAAAAAwEQABgAAAA1AAAA//////////8YAAAAAgEQAEwAAAA2AAAA//////////8YAAAAFAAUAAIAAAAAAAAAMgAAAAAAAAD/////CAAAAcoAEX8yAAAAAwAAAC4AAAAIAAADLgAAAAMBEAAYAAAANgAAAP//////////GAAAAAIBEABMAAAAOQAAAP//////////GAAAABQAFAACAAAAAAAAADIAAAAAAAAA/////wgAAAHKABF/MgAAAAMAAAAtAAAACAAAAy0AAAADARAAGAAAADkAAAD//////////xgAAAACARAAYAAAAD0AAAD//////////zgAAAAUABQAAwAAAAAAAAAyAAAAAwAAACUAAAAIAAADJQAAADIAAAAEAAAA/////wgAABIAAAAAMgAAAAUAAAAwAAAACAAAAzAAAAADARAAGAAAAD0AAAD//////////zgAAAADARAAGAAAABQAAAD//////////yMAAAADARAAGAAAAAIAAAD//////////zQAAAABARAAGAAAAAIAAAD/////GQAAADIAAAA="

let expected = """
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="18" android:versionName="2.8.0" android:installLocation="0" android:compileSdkVersion="28" android:compileSdkVersionCodename="9" package="de.cineaste.android" platformBuildVersionCode="28" platformBuildVersionName="9">
    <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28">
    </uses-sdk>
    <supports-screens android:largeScreens="true" android:xlargeScreens="true">
    </supports-screens>
    <uses-permission android:name="android.permission.INTERNET">
    </uses-permission>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE">
    </uses-permission>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE">
    </uses-permission>
    <application android:theme="@7F110006" android:label="@7F100029" android:icon="@7F0D0000" android:allowBackup="true" android:supportsRtl="true" android:fullBackupContent="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory">
        <activity android:name="de.cineaste.android.MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN">
                </action>
                <category android:name="android.intent.category.LAUNCHER">
                </category>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW">
                </action>
                <category android:name="android.intent.category.DEFAULT">
                </category>
                <category android:name="android.intent.category.BROWSABLE">
                </category>
                <data android:scheme="http" android:host="www.cineaste.de">
                </data>
            </intent-filter>
        </activity>
        <activity android:theme="@7F1100CA" android:name="de.cineaste.android.activity.MovieDetailActivity">
        </activity>
        <activity android:name="de.cineaste.android.activity.MovieSearchActivity">
        </activity>
        <activity android:name="de.cineaste.android.activity.AboutActivity">
        </activity>
        <activity android:name="de.cineaste.android.activity.PosterActivity">
        </activity>
        <activity android:name="de.cineaste.android.activity.SeriesSearchActivity">
        </activity>
        <activity android:theme="@7F1100CA" android:name="de.cineaste.android.activity.SeriesDetailActivity">
        </activity>
        <activity android:theme="@7F1100CA" android:name="de.cineaste.android.activity.SeasonDetailActivity">
        </activity>
        <provider android:name="com.squareup.picasso.PicassoProvider" android:exported="false" android:authorities="de.cineaste.android.com.squareup.picasso">
        </provider>
    </application>
</manifest>
"""
