#if !canImport(ObjectiveC)
import XCTest

extension AXMLtoXMLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AXMLtoXMLTests = [
        ("testAXMLConversion", testAXMLConversion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AXMLtoXMLTests.__allTests__AXMLtoXMLTests),
    ]
}
#endif
