name: Release

on:
  push:
     tags:
     - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@master

    - run: swift build -c release

    - run: mv .build/release/axml-to-xml axml-to-xml

    - run: zip axml-to-xml-${{ matrix.os }}.zip axml-to-xml

    - name: Release
      uses: softprops/action-gh-release@master
      with:
        files: axml-to-xml-${{ matrix.os }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
