name: test

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  test:
    strategy:
      matrix:
        os:
          # Ubuntu won't work until this is rolled out: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
          # - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master

    - name: Cache Dependencies
      uses: actions/cache@master
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - run: swift test


  swiftlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run SwiftLint Checks
      uses: norio-nomura/action-swiftlint@3.1.0
      with:
        args: --strict
